title: Hello, world! I'm Ayush Sharma
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/Salesforce-spices" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: AyushSh06594329 #if your site has a twitter account, enter it here

# Author Settings
author: Ayush Sharma # add your name
author-img: my-img.jpg # add your photo
about-author: I have been working as Salesforce developer for around 3 years, Always interested in learning new Technologies. # add description
social-twitter: AyushSh06594329 # add your Twitter handle
social-facebook: Ayush1996 # add your Facebook handle
social-github: AyuSharma-dev # add your Github handle
social-linkedin: ayush-sharma-75b55613a # add your Linkedin handle
social-email: ayusharmadev@gmail.com # add your Email address

# Disqus
discus-identifier: ayush # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
